<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Elehko.Dotkiln.Engine</RootNamespace>
    <PackageId>Elehko.Dotkiln.Engine</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elehko.Dotkiln.Core\Elehko.Dotkiln.Core.csproj" />
  </ItemGroup>
</Project>
