<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotkiln</ToolCommandName>
    <RootNamespace>Elehko.Dotkiln.Cli</RootNamespace>
    <PackageId>Elehko.Dotkiln.Cli</PackageId>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Elehko.Dotkiln.Core\Elehko.Dotkiln.Core.csproj" />
    <ProjectReference Include="..\Elehko.Dotkiln.Engine\Elehko.Dotkiln.Engine.csproj" />
    <ProjectReference Include="..\Elehko.Dotkiln.Updates\Elehko.Dotkiln.Updates.csproj" />
  </ItemGroup>
</Project>
